# A configuration file for our Quality Infrastructure builds: https://wiki.gpii.net/w/Quality_Infrastructure
app_name: gpii-handlebars

git_repository: https://github.com/the-t-in-rtf/gpii-handlebars.git

email: tony@raisingthefloor.org

env_runtime: linux-desktop

app_start_service: false

software_stack: nodejs

software_stack_version: 4.3.1

setup:
  - sudo npm install -g bower
  - npm install

commands:
  - npm test