language: node_js
node_js:
  - 4
env:
  - CXX=g++-4.8
addons:
  firefox: "46.0"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
    - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
script:
  - BROWSERS=firefox npm test